name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version.'
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: true
      - name: Compile Release Binaries
        run: |
          dotnet publish "Diffraction Monte-Carlo Integration.UI" -c Release -r win-x64 -o publish/win-cli-x64 -p:PublishSingleFile=true --self-contained false
      - name: Upload Windows-x64 Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: publish/win-cli-x64/Diffraction Monte-Carlo Integration.UI.exe
          asset_name: Diffraction Monte-Carlo Integration.exe
          asset_content_type: application/exe
